# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_buffering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureangle',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furnitureangle',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
